spring.application.name=backend
# Jpa
# T?o t?p application-vars.properties và nh?p tên ng??i
# dùng, m?t kh?u và URL c? s? d? li?u vào ?ó.

#do produkcji
#spring.datasource.url=jdbc:h2:file:/data/demo

#do testów
spring.datasource.url=jdbc:h2:mem:testdb

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Hibernate
spring.jpa.hibernate.ddl-auto=update

# H2
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
