spring.application.name=backend
# Jpa
# T?o t?p application-vars.properties và nh?p tên ng??i
# dùng, m?t kh?u và URL c? s? d? li?u vào ?ó.
spring.profiles.active=vars
spring.datasource.username=${db.user}
spring.datasource.password=${db.password}
spring.datasource.url=${db.url}

#Hibernate
spring.jpa.hibernate.ddl-auto=update

# H2
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
