spring.application.name=backend
# Jpa
# T?o t?p application-vars.properties và nh?p tên ng??i
# dùng, m?t kh?u và URL c? s? d? li?u vào ?ó.

#do produkcji
#spring.datasource.url=jdbc:h2:file:/data/demo

#do testów
spring.datasource.url=${db.url}

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${db.username}
spring.datasource.password=${db.pass}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.profiles.active=vars

# File
spring.servlet.multipart.max-file-size=10MB

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# H2
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
