INSERT INTO movie (title, description, production_date) VALUES
                                                            ('Incepcja', 'Dom Cobb to wybitny specjalista w niezwykle niebezpiecznej dziedzinie szpiegostwa przemysłowego: ekstrakcji. Kradnie on bezcenne sekrety z najgłębszych zakamarków ludzkiej podświadomości podczas fazy snu, kiedy umysł jest najbardziej bezbronny. Choć jego niezwykłe umiejętności uczyniły go najbardziej pożądanym graczem w zdradzieckim świecie korporacyjnego szpiegostwa, sprawiły również, że stał się międzynarodowym zbiegiem, który stracił wszystko, co kochał. Teraz Cobb otrzymuje szansę na odkupienie. Ostatnie zadanie może przywrócić mu dawne życie, ale tylko pod warunkiem, że dokona niemożliwego – incepcji. Zamiast idealnej kradzieży, Cobb i jego zespół specjalistów muszą zaszczepić nową ideę w umyśle celu. Jeśli im się uda, będzie to zbrodnia doskonała. Jednak żadne planowanie nie jest w stanie przygotować ich na spotkanie z niebezpiecznym wrogiem, który zdaje się przewidywać każdy ich ruch.', '2010-07-16'),

                                                            ('Matrix', 'Thomas A. Anderson prowadzi podwójne życie. W dzień jest przeciętnym programistą w dużej korporacji, a nocami staje się genialnym hakerem posługującym się pseudonimem Neo. Od dłuższego czasu dręczy go poczucie, że z otaczającym go światem jest coś nie tak. Poszukując odpowiedzi, trafia na ślad tajemniczego Morfeusza, uważanego za najniebezpieczniejszego człowieka na Ziemi. Gdy w końcu dochodzi do ich spotkania, Neo staje przed najważniejszym wyborem w życiu: połknąć niebieską pigułkę i wrócić do bezpiecznej, choć fałszywej rzeczywistości, czy czerwoną, by poznać bolesną prawdę. Okazuje się, że świat, który zna, to tylko iluzja – potężna symulacja komputerowa znana jako Matrix, stworzona przez inteligentne maszyny w celu zniewolenia ludzkości i czerpania z niej energii. Neo dołącza do grupy rebeliantów, odkrywając w sobie niezwykłe umiejętności.', '1999-03-31'),

                                                            ('Ojciec Chrzestny', 'Oparta na bestsellerowej powieści Mario Puzo, ta epicka opowieść gangsterska kronikuje burzliwe losy rodziny Corleone w powojennym Nowym Jorku. Na czele potężnego syndykatu stoi charyzmatyczny i szanowany Don Vito Corleone, człowiek kierujący się własnym, surowym kodeksem honorowym. Kiedy Don odrzuca lukratywną ofertę wejścia w nowo powstający rynek handlu narkotykami, staje się celem brutalnego zamachu, który wstrząsa posadami nowojorskiego półświatka. Wybucha krwawa wojna mafijnych rodzin. W obliczu kryzysu ciężar ratowania imperium spada na barki jego synów: porywczego i brutalnego Sonny''ego oraz najmłodszego Michaela – odznaczonego bohatera wojennego, który przez całe życie starał się dystansować od nielegalnych interesów rodziny. Tragiczny splot wydarzeń zmusza jednak Michaela do porzucenia swoich ideałów. Obserwujemy jego powolną, lecz nieuniknioną transformację z idealisty w bezwzględnego bossa mafii.', '1972-03-14'),

                                                            ('Matrix Reaktywacja', 'Trwa desperacka walka o przetrwanie ludzkości. Syjon, ostatnie podziemne miasto wolnych ludzi, przygotowuje się na najgorsze – armia maszyn wysłała ćwierć miliona Strażników, by przebili się przez skorupę ziemi i zniszczyli rebeliantów. Mając zaledwie 72 godziny do ostatecznej inwazji, Neo, Trinity i Morfeusz muszą przyspieszyć swoje działania wewnątrz Matrixa. Neo, którego moce znacznie wzrosły, wciąż poszukuje odpowiedzi u Wyroczni, która kieruje go w stronę tajemniczego Twórcy Kluczy i Architekta samego systemu. W międzyczasie pojawia się nowe, nieprzewidziane zagrożenie. Były Agent Smith nie został całkowicie zniszczony. Odłączył się od systemu, stając się niekontrolowanym wirusem potrafiącym klonować samego siebie. Z rosnącą armią replikantów, Smith staje się potężnym zagrożeniem nie tylko dla rebeliantów, ale również dla samych maszyn.', '2003-05-15'),

                                                            ('Matrix Rewolucje', 'Epickie zwieńczenie trylogii, w którym walka między ludźmi a maszynami osiąga punkt kulminacyjny. Armia maszyn przypuszcza frontalny, brutalny szturm na doki Syjonu. Zdesperowani obrońcy miasta, używając potężnych maszyn bojowych APU i resztek swojego arsenału, stają do nierównej i krwawej walki, mając nadzieję kupić trochę czasu. Tymczasem Neo uświadamia sobie, że ostateczne rozwiązanie konfliktu nie leży w walce zbrojnej. Wraz z Trinity wyrusza w samobójczą misję statkiem Logos prosto do serca terytorium wroga – Miasta Maszyn. Jego celem jest zawarcie bezprecedensowego paktu z przywódcą maszyn. Jedyną kartą przetargową Neo jest obietnica powstrzymania programu Smith, który wyrwał się spod wszelkiej kontroli, zainfekował niemal cały cyfrowy świat i zagraża bezpowrotnemu zniszczeniu obu cywilizacji.', '2003-11-05'),

                                                            ('Mroczny Rycerz', 'Gotham City w końcu zaczyna oddychać z ulgą. Dzięki nieoficjalnej współpracy Batmana, porucznika Jima Gordona oraz nowo wybranego prokuratora okręgowego Harveya Denta, rozbicie potężnych syndykatów przestępczych staje się faktem. Trio systematycznie niszczy struktury mafii, przejmując ich brudne pieniądze. Zdesperowani i zapędzeni w kozi róg bossowie półświatka, szukając ratunku, przyjmują ofertę od tajemniczego, psychopatycznego przestępcy o pseudonimie Joker. Ten genialny anarchista w przerażającym makijażu nie dba o pieniądze – jego jedynym celem jest udowodnienie, że w każdym człowieku drzemie zło, a moralność to tylko żart. Joker rozpętuje w mieście niespotykaną spiralę chaosu, zmuszając Batmana do stąpania po cienkiej linii między byciem bohaterem a mścicielem. Konflikt doprowadzi do dramatycznego upadku Białego Rycerza Gotham.', '2008-07-18'),

                                                            ('Władca Pierścieni: Drużyna Pierścienia', 'Spokojne życie w sielskim Shire zostaje brutalnie przerwane, gdy stary hobbit Bilbo Baggins przekazuje swojemu siostrzeńcowi, Frodowi, niezwykły pierścień. Czarodziej Gandalf Szary odkrywa przerażającą prawdę: jest to Jedyny Pierścień, potężny artefakt wykuty tysiące lat temu przez Mrocznego Władcę Saurona, by zniewolić ludy Śródziemia. Sauron przebudził się, a jego mroczne siły gorączkowo poszukują zgubionego klejnotu. Aby zapobiec zagładzie, Pierścień musi zostać zniszczony, co jest możliwe tylko w miejscu jego powstania – w ogniu Góry Przeznaczenia w sercu nieprzyjaznego Mordoru. Podczas narady w elfickim Rivendell, Frodo zgłasza się na ochotnika. Wokół niego tworzy się niezwykła Drużyna Pierścienia, w skład której wchodzą przedstawiciele wolnych ras: ludzie Aragorn i Boromir, elf Legolas, krasnolud Gimli, czarodziej Gandalf oraz hobbici.', '2001-12-19'),

                                                            ('Pulp Fiction', 'Przełomowe dzieło Quentina Tarantino, które zredefiniowało kino lat dziewięćdziesiątych dzięki nieliniowej narracji, błyskotliwym dialogom i mieszance popkultury z brutalną przemocą. Film splata ze sobą trzy odrębne, lecz przecinające się historie z podziemia Los Angeles. W pierwszej śledzimy losy Vincenta Vegi i Julesa Winnfielda, dwóch elokwentnych płatnych morderców na usługach potężnego mafioza, Marsellusa Wallace''a. Vincent otrzymuje zadanie: ma zająć się żoną szefa, Mią, co kończy się dramatyczną walką o jej życie. Druga historia skupia się na Butchu Coolidge''u, starzejącym się bokserze, który bierze łapówkę za przegranie walki, ale oszukuje bossa, by odzyskać bezcenny złoty zegarek ojca. W tle przewija się również motyw napadu na restaurację przez dwójkę drobnych złodziejaszków.', '1994-10-14'),
                                                            ('Michael', 'Filmowa opowieść o życiu i dziedzictwie jednego z najbardziej wpływowych artystów w historii – Michaela Jacksona. Produkcja przybliża jego drogę na szczyt, od występów z rodzinnym zespołem Jackson Five, przez solowe triumfy, aż po skomplikowane życie osobiste Króla Popu.', '2026-04-24'),
                                                            ('The Amazing Digital Circus: The Last Act','Internetowy fenomen "The Amazing Digital Circus" doczeka się długo wyczekiwanego finału w formie pełnometrażowego seansu kinowego! „Ostatni akt” łączy odcinek 8 z zupełnie nowym, godzinnym odcinkiem 9, który fani zobaczą jako pierwsi. Gdy Caine znika, a cyrk pogrąża się w mroku, bohaterom pozostają jedynie błędy i traumy z przeszłości. W obliczu nieuchronnej wieczności odkrywają prawdę o Cyfrowym Cyrku i jego historii. Czy zaakceptują to, co odkryją… czy zdecydują się na inne wyjście? Na pewno ktoś rzuci coś zabawnego… bo to zakończenie nie może być aż tak przygnębiające, prawda?','2026-06-04');
INSERT INTO category (name, description) VALUES
                                             ('Sci-Fi', 'Filmy fantastycznonaukowe, alternatywne rzeczywistości, zaawansowana technologia'),
                                             ('Thriller', 'Trzymające w napięciu thrillery psychologiczne i sensacyjne'),
                                             ('Kryminał', 'Historie gangsterskie, mafijne porachunki i świat przestępczy'),
                                             ('Dramat', 'Głębokie wątki osobiste, konflikty moralne i dramatyczne wybory życiowe'),
                                             ('Akcja', 'Szybkie tempo, widowiskowe starcia i pościgi'),
                                             ('Fantasy', 'Magiczne światy, epickie wyprawy i mityczne stworzenia'),
                                             ('Biograficzny', 'Historie oparte na faktach, przedstawiające losy autentycznych postaci'),
                                             ('Muzyczny', 'Filmy skupione wokół muzyki, tańca i historii artystów');


INSERT INTO categoryxmovie (movie_id, category_id) VALUES
(1, 1), (1, 2), (1, 5),
(2, 1), (2, 5),
(3, 3), (3, 4),
(4, 1), (4, 5),
(5, 1), (5, 5),
(6, 5), (6, 3), (6, 2),
(7, 6), (7, 5),
(8, 3), (8, 4),
(9, 7), (9, 4), (9, 8),
(10,1), (10,5);

INSERT INTO movie (title, description, production_date) VALUES
                                                            ('Interstellar', 'W obliczu globalnego kryzysu żywnościowego, zespół astronautów wyrusza w podróż przez tunel czasoprzestrzenny, aby znaleźć nową planetę nadającą się do zasiedlenia przez ludzkość. Film eksploruje granice fizyki, relacje ojca z córką oraz determinację przetrwania gatunku.', '2014-11-07'),
                                                            ('Skazani na Shawshank', 'Historia niesłusznie skazanego bankiera, Andy’ego Dufresne’a, który trafia do więzienia Shawshank. Przez lata zyskuje szacunek współwięźniów i strażników, nie tracąc przy tym nadziei na odzyskanie wolności i sprawiedliwość.', '1994-09-22'),
                                                            ('Władca Pierścieni: Dwie Wieże', 'Drużyna Pierścienia rozpadła się. Frodo i Sam kontynuują niebezpieczną wędrówkę do Mordoru, śledzeni przez tajemniczego Golluma. Tymczasem Aragorn, Legolas i Gimli stają do walki w obronie królestwa Rohanu przed armią Sarumana.', '2002-12-18'),
                                                            ('Parasite', 'Biedna rodzina infiltruje dom zamożnych Państwa Parków, podszywając się pod wysoko wykwalifikowanych pracowników. Z czasem granica między klasami społecznymi zaczyna się zacierać, prowadząc do nieprzewidywalnego i brutalnego finału.', '2019-05-30'),
                                                            ('Whiplash', 'Młody perkusista marzy o byciu wielkim muzykiem jazzowym. Jego ambicja zostaje wystawiona na próbę, gdy trafia pod skrzydła bezwzględnego nauczyciela, który stosuje brutalne metody nauczania, by wydobyć ze swoich uczniów absolutną doskonałość.', '2014-10-10');

INSERT INTO categoryxmovie (movie_id, category_id) VALUES
                                                       (11, 1), (11, 4),
                                                       (12, 4),
                                                       (13, 6), (13, 5),
                                                       (14, 2), (14, 4),
                                                       (15, 4), (15, 8);

INSERT INTO Account (username, email, password_hash, user_type) VALUES
                                                                  ('Admin', 'admin@gmail.com', '$2a$12$20N2omhFfYiJnVfIGFG4k.tDQGW1fFFZPggGYLjoxbNeDp2egaXtu', 2);